export const ACCESS_TOKEN_COOKIE = "accessToken";
export const REFRESH_TOKEN_COOKIE = "refreshToken";

export const ACCESS_TOKEN_STORAGE_KEY = ACCESS_TOKEN_COOKIE;
export const REFRESH_TOKEN_STORAGE_KEY = REFRESH_TOKEN_COOKIE;
